[command]
name = "chown"
description = "Change file owner and group"

[[command.flags]]
name = "-R"
description = "Operate recursively"

[[command.flags]]
name = "-v"
description = "Output for every file processed"

[[command.flags]]
name = "-h"
description = "Affect symbolic links"

[[command.flags]]
name = "--changes"
short = "-c"
description = "Report only when changes made"
os = "linux"

[[command.flags]]
name = "--reference"
arg = "FILE"
description = "Use reference file's owner"
os = "linux"
