[command]
name = "chown"
description = "Change file owner and group"

[[command.flags]]
name = "--recursive"
short = "-R"
description = "Operate recursively"

[[command.flags]]
name = "--verbose"
short = "-v"
description = "Output for every file processed"

[[command.flags]]
name = "--no-dereference"
short = "-h"
description = "Affect symbolic links"

[[command.flags]]
name = "--changes"
short = "-c"
description = "Report only when changes made"

[[command.flags]]
name = "--reference"
arg = "FILE"
description = "Use reference file's owner"
