[command]
name = "cmake"
description = "Cross-platform build system"

[[command.flags]]
name = "-S"
arg = "PATH"
description = "Source directory"

[[command.flags]]
name = "-B"
arg = "PATH"
description = "Build directory"

[[command.flags]]
name = "--build"
arg = "DIR"
description = "Build a project"

[[command.flags]]
name = "--install"
arg = "DIR"
description = "Install a project"

[[command.flags]]
name = "-G"
arg = "GENERATOR"
description = "Specify generator"

[[command.flags]]
name = "-D"
arg = "VAR=VALUE"
description = "Create cache entry"

[[command.flags]]
name = "--preset"
arg = "NAME"
description = "Use a preset"

[[command.flags]]
name = "-j"
arg = "NUM"
description = "Parallel build jobs"

[[command.flags]]
name = "--target"
arg = "TARGET"
description = "Build specific target"
