[command]
name = "crontab"
description = "Manage user cron jobs"

[[command.flags]]
name = "-e"
description = "Edit crontab"

[[command.flags]]
name = "-l"
description = "List crontab"

[[command.flags]]
name = "-r"
description = "Remove crontab"

[[command.flags]]
name = "-u"
arg = "USER"
description = "Specify user"
