[command]
name = "cut"
description = "Remove sections from lines"

[[command.flags]]
name = "-d"
arg = "DELIM"
description = "Set field delimiter"

[[command.flags]]
name = "-f"
arg = "FIELDS"
description = "Select fields by number"

[[command.flags]]
name = "-c"
arg = "CHARS"
description = "Select characters by position"

[[command.flags]]
name = "--complement"
description = "Complement the selection"
os = "linux"

[[command.flags]]
name = "-s"
description = "Skip lines without delimiter"
