[command]
name = "date"
description = "Display or set date and time"

[[command.flags]]
name = "-d"
arg = "STRING"
description = "Display time described by STRING"
os = "linux"

[[command.flags]]
name = "-u"
description = "Display UTC time"

[[command.flags]]
name = "-R"
description = "Output RFC 2822 format"

[[command.flags]]
name = "-I"
arg = "SPEC"
description = "Output ISO 8601 format"

[[command.flags]]
name = "-r"
arg = "FILE"
description = "Display last modification time of FILE"

[[command.flags]]
name = "-v"
arg = "ADJUST"
description = "Adjust date value"
os = "macos"
