[command]
name = "file"
description = "Determine file type"

[[command.flags]]
name = "--brief"
short = "-b"
description = "Omit filename in output"

[[command.flags]]
name = "--mime-type"
short = "-i"
description = "Show MIME type"

[[command.flags]]
name = "-z"
description = "Look inside compressed files"

[[command.flags]]
name = "-L"
description = "Follow symlinks"

[[command.flags]]
name = "-f"
arg = "FILE"
description = "Read filenames from file"
