[command]
name = "flake8"
description = "Python style guide enforcer"

[[command.flags]]
name = "--max-line-length"
arg = "N"
description = "Max line length"

[[command.flags]]
name = "--extend-ignore"
arg = "CODES"
description = "Additional error codes to ignore"

[[command.flags]]
name = "--ignore"
arg = "CODES"
description = "Error codes to ignore"

[[command.flags]]
name = "--exclude"
arg = "PATHS"
description = "Paths to exclude"

[[command.flags]]
name = "--select"
arg = "CODES"
description = "Error codes to check"

[[command.flags]]
name = "--config"
arg = "FILE"
description = "Configuration file"

[[command.flags]]
name = "--count"
description = "Print total number of errors"

[[command.flags]]
name = "--statistics"
description = "Count and print errors per code"

[[command.flags]]
name = "--format"
arg = "FORMAT"
description = "Output format (default, pylint)"

[[command.flags]]
name = "--per-file-ignores"
arg = "SPEC"
description = "Per-file error code ignores"

[[command.flags]]
name = "--show-source"
description = "Show source code for each error"

[[command.flags]]
name = "--max-complexity"
arg = "N"
description = "McCabe complexity threshold"
