[command]
name = "head"
description = "Output first part of files"

[[command.flags]]
name = "-n"
arg = "NUM"
description = "Number of lines to output"

[[command.flags]]
name = "-c"
arg = "NUM"
description = "Number of bytes to output"

[[command.flags]]
name = "-q"
description = "Never print headers"
