[command]
name = "hostname"
description = "Show or set system hostname"

[[command.flags]]
name = "-f"
description = "Display FQDN"

[[command.flags]]
name = "-i"
description = "Display IP address"

[[command.flags]]
name = "-s"
description = "Display short hostname"
