[command]
name = "lazygit"
description = "Terminal UI for git"

[[command.flags]]
name = "--use-config-file"
short = "-ucf"
arg = "FILE"
description = "Custom config file"

[[command.flags]]
name = "--path"
short = "-p"
arg = "PATH"
description = "Path to git repository"

[[command.flags]]
name = "--filter"
short = "-f"
arg = "PATH"
description = "Filter commits by path"

[[command.flags]]
name = "--git-dir"
arg = "DIR"
description = "Custom git directory"

[[command.flags]]
name = "--work-tree"
arg = "DIR"
description = "Custom working tree"

[[command.flags]]
name = "--version"
short = "-v"
description = "Print version"

[[command.flags]]
name = "--debug"
short = "-d"
description = "Run in debug mode"

[[command.flags]]
name = "--log"
short = "-l"
description = "Enable file logging"
