[command]
name = "ln"
description = "Create links between files"

[[command.flags]]
name = "-s"
description = "Create symbolic link"

[[command.flags]]
name = "-f"
description = "Remove existing destination"

[[command.flags]]
name = "-v"
description = "Explain what is being done"

[[command.flags]]
name = "--relative"
short = "-r"
description = "Create relative symbolic link"
os = "linux"

[[command.flags]]
name = "-n"
description = "Do not dereference symlinks"
