[command]
name = "prettier"
description = "Opinionated code formatter"

[[command.flags]]
name = "--write"
short = "-w"
description = "Edit files in place"

[[command.flags]]
name = "--check"
short = "-c"
description = "Check if files are formatted"

[[command.flags]]
name = "--config"
arg = "FILE"
description = "Configuration file"

[[command.flags]]
name = "--single-quote"
description = "Use single quotes"

[[command.flags]]
name = "--tab-width"
arg = "N"
description = "Spaces per indent level"

[[command.flags]]
name = "--trailing-comma"
arg = "WHEN"
description = "Trailing commas (all, es5, none)"

[[command.flags]]
name = "--print-width"
arg = "N"
description = "Line wrap width"

[[command.flags]]
name = "--no-semi"
description = "Omit semicolons"

[[command.flags]]
name = "--parser"
arg = "PARSER"
description = "Force parser (babel, typescript, css, json, html, markdown)"

[[command.flags]]
name = "--ignore-path"
arg = "FILE"
description = "Ignore file path"

[[command.flags]]
name = "--list-different"
short = "-l"
description = "List unformatted files"

[[command.flags]]
name = "--cache"
description = "Only format changed files"

[[command.flags]]
name = "--no-config"
description = "Don't look for config file"

[[command.flags]]
name = "--bracket-same-line"
description = "Put > on the same line"
