[command]
name = "ruby"
description = "Ruby interpreter"

[[command.flags]]
name = "-e"
arg = "CODE"
description = "Execute one-liner script"

[[command.flags]]
name = "-w"
description = "Turn on warnings"

[[command.flags]]
name = "-c"
description = "Check syntax only"

[[command.flags]]
name = "-I"
arg = "DIR"
description = "Add directory to load path"

[[command.flags]]
name = "-r"
arg = "LIB"
description = "Require library before executing"

[[command.flags]]
name = "-n"
description = "Loop over input (like sed)"

[[command.flags]]
name = "-p"
description = "Loop over input and print"

[[command.flags]]
name = "-v"
description = "Print version and enable verbose"

[[command.flags]]
name = "--version"
description = "Print version"
