[command]
name = "scp"
description = "Secure copy over SSH"

[[command.flags]]
name = "-r"
description = "Recursively copy directories"

[[command.flags]]
name = "-P"
arg = "PORT"
description = "SSH port"

[[command.flags]]
name = "-i"
arg = "FILE"
description = "Identity file"

[[command.flags]]
name = "-C"
description = "Enable compression"

[[command.flags]]
name = "-l"
arg = "LIMIT"
description = "Limit bandwidth in Kbit/s"

[[command.flags]]
name = "-o"
arg = "OPTION"
description = "SSH option"

[[command.flags]]
name = "-p"
description = "Preserve file attributes"

[[command.flags]]
name = "-q"
description = "Quiet mode"

[[command.flags]]
name = "-v"
description = "Verbose mode"
