[command]
name = "screen"
description = "Terminal multiplexer"

[[command.flags]]
name = "-S"
arg = "NAME"
description = "Session name"

[[command.flags]]
name = "-r"
arg = "NAME"
description = "Reattach session"

[[command.flags]]
name = "-ls"
description = "List sessions"

[[command.flags]]
name = "-d"
description = "Detach session"

[[command.flags]]
name = "-x"
description = "Multi-display attach"

[[command.flags]]
name = "-R"
description = "Reattach or create"

[[command.flags]]
name = "-dm"
description = "Start detached"

[[command.flags]]
name = "-L"
description = "Enable logging"

[[command.flags]]
name = "-wipe"
description = "Clean dead sessions"
