[command]
name = "sd"
description = "Intuitive find-and-replace tool"

[[command.flags]]
name = "--preview"
short = "-p"
description = "Preview changes"

[[command.flags]]
name = "--string-mode"
short = "-s"
description = "Treat as literal strings"

[[command.flags]]
name = "--flags"
short = "-f"
arg = "FLAGS"
description = "Regex flags (e.g. 'i' for case-insensitive)"
