[command]
name = "tail"
description = "Output last part of files"

[[command.flags]]
name = "-n"
arg = "NUM"
description = "Number of lines to output"

[[command.flags]]
name = "-f"
description = "Follow file output as it grows"

[[command.flags]]
name = "-F"
description = "Follow with retry on rename"

[[command.flags]]
name = "-c"
arg = "NUM"
description = "Number of bytes to output"

[[command.flags]]
name = "-q"
description = "Never print headers"

[[command.flags]]
name = "--pid"
arg = "PID"
description = "Terminate after process dies"
