[command]
name = "traceroute"
description = "Print route packets take to host"

[[command.flags]]
name = "-n"
description = "Show numeric addresses"

[[command.flags]]
name = "-m"
arg = "N"
description = "Maximum number of hops"

[[command.flags]]
name = "-w"
arg = "SECONDS"
description = "Wait time per probe"

[[command.flags]]
name = "-q"
arg = "N"
description = "Probes per hop"

[[command.flags]]
name = "-I"
description = "Use ICMP ECHO"

[[command.flags]]
name = "-T"
description = "Use TCP SYN"

[[command.flags]]
name = "-p"
arg = "PORT"
description = "Destination port"
