[command]
name = "uname"
description = "Print system information"

[[command.flags]]
name = "-a"
description = "Print all information"

[[command.flags]]
name = "-s"
description = "Print kernel name"

[[command.flags]]
name = "-r"
description = "Print kernel release"

[[command.flags]]
name = "-m"
description = "Print machine hardware name"

[[command.flags]]
name = "-n"
description = "Print network hostname"

[[command.flags]]
name = "-v"
description = "Print kernel version"

[[command.flags]]
name = "-p"
description = "Print processor type"
