[command]
name = "uptime"
description = "Show system uptime and load"

[[command.flags]]
name = "-p"
description = "Show uptime in human-readable format"
os = "linux"

[[command.flags]]
name = "-s"
description = "Show system up since"
os = "linux"
