[command]
name = "vite"
description = "Next generation frontend build tool"

[[command.subcommands]]
name = "dev"
description = "Start dev server"
[[command.subcommands.flags]]
name = "--port"
arg = "PORT"
description = "Server port"
[[command.subcommands.flags]]
name = "--host"
arg = "HOST"
description = "Server host"
[[command.subcommands.flags]]
name = "--open"
description = "Open browser on start"
[[command.subcommands.flags]]
name = "--strictPort"
description = "Exit if port is in use"

[[command.subcommands]]
name = "build"
description = "Build for production"
[[command.subcommands.flags]]
name = "--outDir"
arg = "DIR"
description = "Output directory"
[[command.subcommands.flags]]
name = "--sourcemap"
description = "Generate source maps"
[[command.subcommands.flags]]
name = "--minify"
arg = "TYPE"
description = "Minifier (esbuild, terser, false)"

[[command.subcommands]]
name = "preview"
description = "Preview production build"
[[command.subcommands.flags]]
name = "--port"
arg = "PORT"
description = "Server port"

[[command.flags]]
name = "--config"
short = "-c"
arg = "FILE"
description = "Config file path"

[[command.flags]]
name = "--mode"
short = "-m"
arg = "MODE"
description = "Set env mode"

[[command.flags]]
name = "--debug"
arg = "FEAT"
description = "Show debug logs"
