[command]
name = "wc"
description = "Word, line, and byte count"

[[command.flags]]
name = "-l"
description = "Print line count"

[[command.flags]]
name = "-w"
description = "Print word count"

[[command.flags]]
name = "-c"
description = "Print byte count"

[[command.flags]]
name = "-m"
description = "Print character count"

[[command.flags]]
name = "-L"
description = "Print max line length"
